In [1]:
import numpy as np

# Tạo một mảng
arr = np.array([1, 2, 3])

# In mảng
print(arr)

# In ra một phần tử từ mảng (ví dụ: phần tử thứ hai)
element = arr[1]
print(f"Phần tử thứ hai trong mảng: {element}")

[1 2 3]
Phần tử thứ hai trong mảng: 2


In [2]:
import numpy as np

# Tạo một mảng 2 chiều (ma trận)
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# In ra ma trận
print("Ma trận:")
print(matrix)

# In ra một phần tử từ ma trận (ví dụ: phần tử ở hàng 2, cột 3)
element = matrix[1, 2]
print(f"Phần tử ở hàng 2, cột 3 trong ma trận: {element}")

Ma trận:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Phần tử ở hàng 2, cột 3 trong ma trận: 6


In [19]:
# Cách tạo mảng

# Tạo một mảng gồm 2 phần tử, mọi giá trị ban đầu là 0.0
a = np.zeros(2)
print(a)  # In ra: [0. 0.]

# Tạo một mảng gồm 2 phần tử, mọi giá trị ban đầu là 1.0
a = np.ones(2)
print(a)  # In ra: [1. 1.]

# Tạo một mảng gồm 2 phần tử, giá trị ban đầu có thể không được thiết lập
a = np.empty(2)
print(a)  # In ra một mảng với giá trị ngẫu nhiên (thường là rất gần với 0.0)

# Tạo một mảng với một dãy số từ 0 đến 3 (có thể điều chỉnh giá trị cuối)
a = np.arange(4)
print(a)  # In ra: [0 1 2 3]

# Tạo một mảng gồm 5 phần tử với giá trị từ 0 đến 10 với khoảng cách đều nhau
a = np.linspace(0, 10, num=5)
print(a)  # In ra: [ 0.   2.5  5.   7.5 10. ]
a = np.linspace(0, 10, num=6)
print(a)  # In ra: [ 0.   2.5  5.   7.5 10. ]
a = np.linspace(0, 15, num=5)
print(a)  # In ra: [ 0.   2.5  5.   7.5 10. ]
a = np.linspace(0, 15, num=6)
print(a)  # In ra: [ 0.   2.5  5.   7.5 10. ]

# Tạo mảng xác định kiểu dữ liệu
x = np.ones(2, dtype=np.int64)
x

[0. 0.]
[1. 1.]
[1. 1.]
[0 1 2 3]
[ 0.   2.5  5.   7.5 10. ]
[ 0.  2.  4.  6.  8. 10.]
[ 0.    3.75  7.5  11.25 15.  ]
[ 0.  3.  6.  9. 12. 15.]


array([1, 1], dtype=int64)

In [4]:
# Thêm, loại bỏ và sắp xếp mảng

import numpy as np

# Tạo mảng ban đầu
arr = np.array([3, 1, 2, 4, 5])
print(arr)

# Thêm một phần tử vào cuối mảng
arr = np.append(arr, 6)
print(arr)

# Loại bỏ phần tử tại vị trí cụ thể
arr = np.delete(arr, 3)
print(arr)

# Sắp xếp mảng theo thứ tự tăng dần
arr = np.sort(arr)
print(arr)

# Sắp xếp mảng theo thứ tự giảm dần
arr = np.sort(arr)[::-1]
print(arr)

[3 1 2 4 5]
[3 1 2 4 5 6]
[3 1 2 5 6]
[1 2 3 5 6]
[6 5 3 2 1]


In [5]:
import numpy as np

# Tạo một mảng 2 chiều
arr = np.array([[3, 1, 2],
                [4, 6, 5],
                [9, 7, 8]])

# Sắp xếp mảng theo hàng (axis=1) theo thứ tự tăng dần
sap_xep_theo_hang = np.sort(arr, axis=1)
print("Sắp xếp theo hàng (axis=1):")
print(sap_xep_theo_hang)

# Sắp xếp mảng theo cột (axis=0) theo thứ tự tăng dần
sap_xep_theo_cot = np.sort(arr, axis=0)
print("\nSắp xếp theo cột (axis=0):")
print(sap_xep_theo_cot)

Sắp xếp theo hàng (axis=1):
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sắp xếp theo cột (axis=0):
[[3 1 2]
 [4 6 5]
 [9 7 8]]


In [6]:
import numpy as np

# Tạo một mảng 2 chiều
arr = np.array([[3, 1, 2],
                [4, 6, 5],
                [9, 7, 8]])

# Sắp xếp mảng theo hàng (axis=1) theo thứ tự giảm dần
sap_xep_theo_hang_giam = -np.sort(-arr, axis=1)
print("Sắp xếp theo hàng (axis=1) giảm dần:")
print(sap_xep_theo_hang_giam)

# Sắp xếp mảng theo cột (axis=0) theo thứ tự giảm dần
sap_xep_theo_cot_giam = -np.sort(-arr, axis=0)
print("\nSắp xếp theo cột (axis=0) giảm dần:")
print(sap_xep_theo_cot_giam)

Sắp xếp theo hàng (axis=1) giảm dần:
[[3 2 1]
 [6 5 4]
 [9 8 7]]

Sắp xếp theo cột (axis=0) giảm dần:
[[9 7 8]
 [4 6 5]
 [3 1 2]]


In [7]:
import numpy as np

# Tạo một mảng 2D
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Sử dụng các thuộc tính để lấy thông tin về mảng
so_chieu = arr.ndim  # Số chiều (2 chiều)
kich_thuoc = arr.size  # Kích thước (tổng số phần tử, 6)
hinh_dang = arr.shape  # Hình dạng (số hàng x số cột, (2, 3))

print("Số chiều:", so_chieu)
print("Kích thước:", kich_thuoc)
print("Hình dạng:", hinh_dang)

Số chiều: 2
Kích thước: 6
Hình dạng: (2, 3)


In [8]:
# Chuyển đổi kiểu dữ liệu
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr_float = arr.astype(float)
print(arr_float)

[1. 2. 3. 4. 5.]


In [9]:
#Thay đổi hình dạng của mảng
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


In [10]:
# Cắt lát mảng
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
sub_arr = arr[1:4]  # Cắt từ phần tử thứ 1 đến 4
print(sub_arr)
sub_arr = arr[:-1]  # ?
print(sub_arr)
sub_arr = arr[-1:]  # ?
print(sub_arr)

[2 3 4]
[1 2 3 4]
[5]


In [11]:
# Chuyển vị mảng
# Để chuyển vị mảng, chúng ta có thể sử dụng .T hoặc hàm numpy.transpose().
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
transposed_arr = arr.T
print(transposed_arr)

[[1 4]
 [2 5]
 [3 6]]


In [12]:
# Nối mảng
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenated_arr = np.concatenate((arr1, arr2))
print(concatenated_arr)

[1 2 3 4 5 6]


In [13]:
# Một số hàm tính toán cơ bản

In [14]:
# Bài giảng về các hàm tính toán cơ bản trong NumPy

# I. Giới thiệu
# - NumPy (Numerical Python) là một thư viện quan trọng trong Python dùng để làm việc với mảng và ma trận.
# - NumPy cung cấp nhiều hàm tính toán cơ bản giúp bạn thực hiện các phép toán số học và thống kê trên mảng.

import numpy as np

# II. Hàm tính tổng (Sum)
# - Hàm numpy.sum() cho phép tính tổng các phần tử trong mảng.
arr = np.array([1, 2, 3, 4, 5])
total = np.sum(arr)
print("Tổng của mảng arr:", total)

# III. Hàm tính trung bình (Mean)
# - Hàm numpy.mean() tính giá trị trung bình của các phần tử trong mảng.
average = np.mean(arr)
print("Giá trị trung bình của mảng arr:", average)

# IV. Hàm tìm giá trị lớn nhất và nhỏ nhất (Max và Min)
# - Hàm numpy.max() và numpy.min() dùng để tìm giá trị lớn nhất và nhỏ nhất trong mảng.
max_value = np.max(arr)
min_value = np.min(arr)
print("Giá trị lớn nhất trong mảng arr:", max_value)
print("Giá trị nhỏ nhất trong mảng arr:", min_value)

# V. Hàm tính độ lệch chuẩn (Standard Deviation)
# - Hàm numpy.std() tính độ lệch chuẩn của mảng, đo lường mức độ phân tán của dữ liệu.
std_deviation = np.std(arr)
print("Độ lệch chuẩn của mảng arr:", std_deviation)

# VI. Hàm tính phương sai (Variance)
# - Hàm numpy.var() tính phương sai của mảng, đo lường mức độ biến thiên của dữ liệu.
variance = np.var(arr)
print("Phương sai của mảng arr:", variance)

# VII. Hàm tính tổng tích chập (Dot Product)
# - Hàm numpy.dot() tính tổng tích chập của hai mảng (vector).
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
dot_product = np.dot(arr1, arr2)
print("Tổng tích chập của arr1 và arr2:", dot_product)

Tổng của mảng arr: 15
Giá trị trung bình của mảng arr: 3.0
Giá trị lớn nhất trong mảng arr: 5
Giá trị nhỏ nhất trong mảng arr: 1
Độ lệch chuẩn của mảng arr: 1.4142135623730951
Phương sai của mảng arr: 2.0
Tổng tích chập của arr1 và arr2: 32
