In [1]:
import cv2
import numpy as np

In [2]:
# Tải ảnh đầu vào
img = cv2.imread('./img/face.png')

# Hiển thị ảnh gốc
cv2.imshow('Ảnh gốc', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
# Tải mô hình đã được huấn luyện từ trước
net = cv2.dnn.readNetFromCaffe(
    './models/deploy.prototxt.txt',
    './models/res10_300x300_ssd_iter_140000_fp16.caffemodel'
)

# Chuẩn bị dữ liệu đầu vào
# img: Đây là ảnh đầu vào mà bạn muốn nhận dạng khuôn mặt. Trong trường hợp của bạn, bạn đã đọc ảnh từ tệp "face.png".
# 1.0: Đây là tỷ lệ co giãn cho ảnh. Trong trường hợp này, ảnh sẽ không bị co giãn hoặc mở rộng, và giữ nguyên kích thước ban đầu.
# (300, 300): Đây là kích thước mà mô hình yêu cầu cho ảnh đầu vào. Mô hình mà bạn đang sử dụng mong muốn ảnh có kích thước 300x300 pixel. Do đó, bạn co giãn hoặc cắt ảnh đầu vào thành kích thước này.
# (104, 177, 123): Đây là giá trị trung bình màu sắc được trừ đi từ mỗi pixel của ảnh. Điều này thường được sử dụng để chuẩn hóa dữ liệu đầu vào. Trong trường hợp này, các giá trị này thường được lấy từ dữ liệu huấn luyện của mô hình.
# swapRB=False: Đây là một cờ để xác định xem có cần hoán đổi các kênh màu đỏ và xanh (Red-Blue) trong ảnh hay không. Trong trường hợp này, bạn đã đặt nó thành False, tức là không hoán đổi kênh mà
blob = cv2.dnn.blobFromImage(img, 1.0, (300, 300), (104, 177, 123), swapRB=False)

# Đặt dữ liệu đầu vào cho mạng
net.setInput(blob)

# Chạy mạng để phát hiện khuôn mặt
faces = net.forward()

# Lấy kích thước của ảnh đầu vào
h = img.shape[0]
w = img.shape[1]

# In thông tin
print(faces.shape)
print(faces[0, 0, 0, ])

# Duyệt từng khuôn mặt đã được phát hiện
for i in range(0, faces.shape[2]):
    confidence = faces[0,0,i,2]
    # Kiểm tra nếu mặt có độ tin cậy là 0.5
    if confidence>0.5:
        # Trích xuất tọa độ
        print(faces[0, 0, i, 3:7])
        startx = int(faces[0, 0, i, 3]*w)
        starty = int(faces[0, 0, i, 4]*h)
        endx = int(faces[0, 0, i, 5]*w)
        endy = int(faces[0, 0, i, 6]*h)
        print(startx, starty, endx, endy)
        
        # Vẽ hình chữ nhật xung quanh khuôn mặt đã phát hiện
        cv2.rectangle(img, (startx, starty), (endx, endy), (0, 255, 0),)
        
        # Hiển thị độ tin cậy
        text = 'Face: {:.2f}%'.format(confidence*100);
        cv2.putText(img, text, (startx, starty-10), cv2.FONT_HERSHEY_PLAIN, 1, (255,255,255),)

# Hiển thị ảnh gốc
cv2.imshow('Kết quả', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

(1, 1, 200, 7)
[0.         1.         0.9999964  0.08431688 0.03673201 0.27289385
 0.21404085]
[0.08431688 0.03673201 0.27289385 0.21404085]
63 36 204 213
[0.40016374 0.02709637 0.5796922  0.2290841 ]
300 27 434 228
[0.7526962 0.7904155 0.9409632 0.9887612]
564 789 705 987
[0.75594413 0.02493154 0.94624543 0.23191439]
566 24 709 231
[0.08840965 0.7984332  0.2506579  0.9847306 ]
66 797 187 983
[0.7299407  0.2731235  0.9186155  0.48587334]
547 272 688 485
[0.749446   0.5421455  0.93323225 0.7356533 ]
562 541 699 734
[0.42464417 0.2903077  0.59998184 0.46850938]
318 290 449 468
[0.07715233 0.29420722 0.24884456 0.47311437]
57 293 186 472
[0.38338947 0.79234743 0.5654873  0.98343265]
287 791 424 982
[0.43102103 0.53480047 0.6274299  0.7348283 ]
323 534 470 734
[0.07509603 0.5484237  0.24415457 0.7226415 ]
56 547 183 721
